Rename extensions -> sglite
HEXRD/hexrd pull request #127
Opened 2020-10-02 18:01 UTC by cjh1

This fixes an issue with develop install on Windows, as the sglite
directory already exists.

2020-10-02 18:01 UTC, cjh1 commented
@joelvbernier This should resolve the dev install issue.

2020-10-02 21:45 UTC, joelvbernier requested changes
The idea of the extensions folder was to have a single place for all the compiled extenstions to go.  Also, sglite is going away, as the new materials package replaces it (and we will no longer need to build the sglite package).  Lastly, the transforms extension has no relation to sglite, and if anything can go into the transforms package folder.

2020-10-05 12:48 UTC, cjh1 commented
OK, I will rework

2020-10-07 17:08 UTC, joelvbernier approved these changes

2020-10-07 17:08 UTC, merged